/srv/lnagovetc/backend/log/web/web.log
/srv/lnagovetc/backend/log/postgres/postgresql.log
/srv/lnagovetc/backend/log/redis/redis.log
/srv/lnagovetc/backend/log/frontend/*.log
{
  daily
  rotate 31
  maxage 31
  missingok
  notifempty
  compress
  delaycompress
  copytruncate
  dateext
}
